server {
    listen 80;
    server_name alparque.onrender.com;

    # Configuración para los archivos estáticos de Django
    location /static/ {
        alias /staticfiles/;
        expires 30d;
    }

    # Configuración para la API de Django o tu aplicación
    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Manejo de errores
    error_log  /Perfiles/logs/nginx_error.log;
    access_log /Perfiles/logs/nginx_access.log;
    
    # Archivo de error 404 personalizado
    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }

    # Archivo de error 500 personalizado
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
        internal;
    }
}
