# Generated by Django 4.1.4 on 2025-02-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlParque', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parque',
            name='imagenes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
