# Generated by Django 4.1.4 on 2025-02-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlParque', '0003_alter_parque_imagenes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividadusuario',
            old_name='fecha_participacion',
            new_name='integranteDesde',
        ),
        migrations.AddField(
            model_name='actividadusuario',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
