# Generated by Django 4.1.4 on 2025-02-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlParque', '0004_rename_fecha_participacion_actividadusuario_integrantedesde_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='integrantes',
        ),
    ]
