# Generated by Django 4.1.4 on 2025-02-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlParque', '0005_remove_actividad_integrantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='integrantes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
