# Generated by Django 4.1.4 on 2025-02-13 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AlParque', '0006_actividad_integrantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='integrantes',
        ),
        migrations.AddField(
            model_name='actividad',
            name='integrantes',
            field=models.ManyToManyField(blank=True, related_name='actividades', to=settings.AUTH_USER_MODEL),
        ),
    ]
