# Generated by Django 4.1.4 on 2025-02-14 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlParque', '0007_remove_actividad_integrantes_actividad_integrantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='integrantes',
        ),
        migrations.AlterField(
            model_name='actividadusuario',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='AlParque.actividad'),
        ),
    ]
