# Generated by Django 4.1.4 on 2025-02-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlParque', '0008_remove_actividad_integrantes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='administrador',
        ),
        migrations.AddField(
            model_name='actividadusuario',
            name='administrador',
            field=models.BooleanField(default=False),
        ),
    ]
